language : python
python:
    - "3.4"
before_install:
    - sudo apt-get update
    - sudo apt-get -y install cmake
    - sudo git clone https://github.com/lloyd/yajl.git
    - cd yajl
    - sudo ./configure
    - sudo make install
    - cd ..
install:
    - sudo pip -H install again
    - sudo pip -H install pytest
script: sudo py.test
