language : python
python:
    - "3.4"
before_install:
    - wget http://www.cmake.org/files/v3.3/cmake-3.3.0.tar.gz
    - tar xzf cmake-3.3.0.tar.gz
    - cd cmake-3.3.0
    - sudo ./configure
    - sudo make
    - sudo make install
    - cd ..
    - PATH=$PATH:/usr/local/lib
    - sudo git clone https://github.com/lloyd/yajl.git
    - cd yajl
    - sudo ./configure
    - sudo make install
    - cd ..
install:
    - pip install again
    - pip install pytest
script: py.test
